### API To Add a Single Card
POST http://localhost:8080/api/cards/single
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJicnVub0B2aXNhLmNvbSIsImlhdCI6MTc2NDQ0MjQwOSwiZXhwIjoxNzY0NTI4ODA5fQ.JHl1vVtWALtVM-5Ylrn4nG0K64QpX-irzn5uFFiMCgs

{
  "cardNumber": "4456897999999990",
  "batchNumber": "LOTE001",
  "lineIdentifier": "C1",
  "numberingInBatch": "000001",
  "lineNumber": 1
}
###